### ISSUE TITLE
won't compile on Arduino IDE 2.3.4?

### ISSUE THREAD

**Issue by romix123** [Dlloydev/Toggle#8]
I get compile errors for the library:
/Users/ronald/Documents/Development/Arduino2/libraries/Toggle/src/Toggle.h:6: error 1: Syntax error, declaration ignored at 'class'
/Users/ronald/Documents/Development/Arduino2/libraries/Toggle/src/Toggle.h:6: syntax error: token -> 'Toggle' ; column 12
/Users/ronald/Documents/Development/Arduino2/libraries/Toggle/src/Toggle.h:11: syntax error: token -> ';' ; column 13
/Users/ronald/Documents/Development/Arduino2/libraries/Toggle/src/Toggle.h:12: error 65: function 'Toggle' already has body
/Users/ronald/Documents/Development/Arduino2/libraries/Toggle/src/Toggle.h:12: syntax error: token -> ';' ; column 23
/Users/ronald/Documents/Development/Arduino2/libraries/Toggle/src/Toggle.h:13: syntax error: token -> '=' ; column 36

What's up?
